@startuml
'https://plantuml.com/class-diagram

Registrer --> Inventory
Registrer --> Basket
Basket *-- BasketEntry
Inventory *-- InventoryItem
BasketEntry --> InventoryItem


class InventoryItem
{
 - String name
 - double regularPrice
 - double salePrice
 - boolean isOnSale
 + String getName()
 + double getRegularPrice()
 + double getSalePrice()
 + boolean isOnSale()
 + double getPriceToUse()
}

class Registrer
{
- Map<String, BasketEntry> entries
+ void scanBasket()
+ double calculateTotals()
printReceipt()
}

class Inventory
{
- Collection<InventoryItem> allItems
- Collection<InventoryItem> saleItems
+ void loadInventory()
- void loadRegularItem()
- void loadSaleItem()
+ Collection<InventoryItem> getRegularItems()
+ Collection<InventoryItem> getSaleItems()
}

class Basket
{
- Map<String, BasketEntry> entries
+ void getItem()
+ Collection<BasketEntry> getEntries()
}

class BasketEntry
{
- InventoryItem item
- int quantity
+ InventoryItem getItem()
+ int getQuantity()
+ void increaseQuantity(int amount)
+ double getPriceToUse()
+ double getTotalSaved()
}
@enduml